// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: user.sql

package database

import (
	"context"
)

const getUserByApiKey = `-- name: GetUserByApiKey :one
SELECT id, created_at, updated_at, api_key, password_string FROM users WHERE api_key = $1
`

func (q *Queries) GetUserByApiKey(ctx context.Context, apiKey string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByApiKey, apiKey)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ApiKey,
		&i.PasswordString,
	)
	return i, err
}
