// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"database/sql"
)

type Note struct {
	ID          int32        `json:"id"`
	Title       string       `json:"title"`
	Content     string       `json:"content"`
	UserID      int32        `json:"user_id"`
	IsFavourite sql.NullBool `json:"is_favourite"`
	CreatedAt   sql.NullTime `json:"created_at"`
}

type User struct {
	ID        int32        `json:"id"`
	Email     string       `json:"email"`
	Password  string       `json:"password"`
	CreatedAt sql.NullTime `json:"created_at"`
}
