// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"database/sql"
)

type Note struct {
	ID          int32
	Title       string
	Content     string
	UserID      int32
	IsFavourite sql.NullBool
	CreatedAt   sql.NullTime
}

type User struct {
	ID        int32
	Email     string
	Password  string
	CreatedAt sql.NullTime
}
